name: thetomharmon
favicon: null
layout_spectrum: 0.8966172430664301
typography_spectrum: 0.8487398023717105
title: Director of Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000908'
    - '#e8d9d6'
    - '#2e5f5a'
    - '#7e0309'
    - '#e35c54'
  brandStrength: 0.2691421729978174
  lightness: 0.1317611129488796
  saturation: 0.7190144604537636
  rhythmicContrast: 0.49549779132939875
purpose: []
